version: "3.9"

services:
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost

  app:
    build: .
    ports:
      - "5000:5000"
